### ISSUE TITLE
Set default directory per entity

### ISSUE THREAD

**Issue by stephanvierkant** [AshleyDawson/DoctrineFlysystemBundle#3]
I'm saving company logos on my Company entity. I'd like to save images to `{$company->id}/{filename}` to prevent users to overwrite each others logos (logo.jpg is a very common name :)).
 
The documentation shows an example using StoreEvent, but the entity isn't passed to that Event. I tried to overwrite `StorableTrait`'s methods, but I couldn't find a good way to modify the directory.

What's the best way to achieve this? Should we add the entity to the StoreEvent?

**Comment by AshleyDawson** [comment]
Hi,

There's an example in the documentation for events that uses a pseudo-random directory prefix for files: https://github.com/AshleyDawson/DoctrineFlysystemBundle#events

To overcome the issue of common filenames, and because this library decouples the storage filename from the original filename, it's possible to use a randomly generated UUID for the storage path. I recommend the following library for that: https://github.com/ramsey/uuid

So, your implementation would look something like:

```
$this->get('event_dispatcher')->addListener(StorageEvents::PRE_STORE, function (StoreEvent $event) {
    $event->setFileStoragePath(sprintf(/%s.%s', (string) Uuid::uuid4(), $event->getUploadedFile()->getClientOriginalExtension()));
});
```

**Comment by stephanvierkant** [comment]
My question was how to set the directory name by using the entity's information. Not (pseudo-)random directory names, but a directory name that makes sense. I'm not using this bundle anymore, so I'm fine with closing this issue.
